### ISSUE TITLE
change event is not firing

### ISSUE THREAD

**Issue by StephenTurley** [PolymerElements/gold-email-input#48] opened 2015-12-07 03:38 UTC
Tried binding to the on-change event within a custom element. The event never seems to fire. I also tired using the `listeners` object within my element config and the behavior was the same. 

I'm using the latest version of the element and chrome. 

```
<gold-email-input name="email" label="Email Address" on-change="_emailChanged" value={{email}} required=true auto-validate error-message="Invalid email address"></gold-email-input>


<script>
     Polymer({
          ...
          _emailChanged: function(event){
		console.log('email has changed!'); //never called
	},
       ...
     });
</script>

```

**Comment by MeTaNoV** [comment] 2015-12-07 08:22
did you tried `on-value-changed="_emailChanged"` ?

**Comment by StephenTurley** [comment] 2015-12-07 13:38
Yes that seems to work. Any idea why the docs claim that the event is `change`? Perhaps that is for something completely different?

**Comment by MeTaNoV** [comment] 2015-12-07 13:56
You would use `on-change` if you worked with the native `input`, which is what is done deep inside with the `iron-input` wrapper which brings magical data-binding! Take a look at the implementation, it is quite instructive! :)

**Comment by StephenTurley** [comment] 2015-12-07 17:07
Sure, thanks. I still feel like this is a documentation defect:
https://elements.polymer-project.org/elements/gold-email-input#change

**Comment by MeTaNoV** [comment] 2015-12-07 17:28
@notwaldorf should the `change` be fired as described in the doc?

**Comment by notwaldorf** [comment] 2015-12-07 23:41
First of all, is this in the shady or shadow DOM? Also, keep in mind `change` is meant to mimic the `input` change event, which only fires when the value is committed by the user (https://developer.mozilla.org/en-US/docs/Web/Events/change). It does _not_ fire when it's updated imperatively.

To check that it works, in the shady DOM (jsbin bin is broken right now, so bear with me), in the demo (https://elements.polymer-project.org/bower_components/gold-email-input/demo/index.html), select one of the `gold-email-inputs`, and add a listener to it:
```
$0.addEventListener('change', function() {console.log('change');} );
```
You will see that when you tab out of an input, or press enter, `change` will be logged to the console. Here's vague proof that it worked (again, sorry for the caveman approach, jsbin is hella down right now):
<img width="454" alt="screen shot 2015-12-07 at 3 38 05 pm" src="https://cloud.githubusercontent.com/assets/1369170/11643407/99a3ba40-9cf8-11e5-8aa9-289b152b1b44.png">


In the Shadow DOM, 'change' is a bit of a problematic event, because it's one of the few that don't get automatically retargetted (http://www.w3.org/TR/shadow-dom/#h-events-that-are-not-leaked-into-ancestor-trees). `PaperInputBehavior` tries to be a little smart, and captures the `change` event from `input`, and re-fires it. However, this means that it will only be available to its direct parent (a demo page, or the custom element that contains `gold-email-input`), but not anywhere else.

I will close this, since I think everything is working as intended.

**Closed by notwaldorf** 2015-12-07 23:41 UTC

**Comment by MeTaNoV** [comment] 2015-12-08 01:16
@notwaldorf Thanks for the complete explanation! Didn't know about the specificities of this category of event!

**Comment by StephenTurley** [comment] 2015-12-08 01:30
Thanks!
